[external_reference]
ac_valve-status = "UF-Air Scour Valve State"
b1-valve-status = "UF-B1 State"
b3w1_valve-status = "UF-B3W1 State"
b3w2-valve-status = "UF-B3W2 State"
conn-b3w1_valve-to-uf_bypass_valve-flow-rate = "UF-Permeate Flow (GPM)"
conn-b3w1_valve-to-uf_bypass_valve-ph = "UF-Permeate pH"
conn-b3w1_valve-to-uf_bypass_valve-pressure = "UF-Permeate Pressure (psi)"
conn-b3w1_valve-to-uf_bypass_valve-toc-ppm = "MULT-TOC-1 (ppm)"
conn-uf-unit-to-reject_valve-pressure = "UF-Reject Pressure (psi)"
feed-pump-electric-current = "UF-Current Draw (A)"
feed-pump-out-flow-rate = "UF-Feed Flow (GPM)"
feed-pump-out-pressure = "UF-Feed Pressure (psi)"
s2_valve-status = "UF-Purge Valve State"
supply-tank-out-flow-rate = "DP1 Flowrate (mL/min)"
uf-feed-tank-temperature = "UF-Feed Temperature (C)"
uf-feed-tank-volume = "UF-Feed Volume (gal)"
uf-unit-out-turbidity = "UF-Turbidity [3] (NTU)"
uf_backwash_pump-status = "UF-Backwash Pump State"
ufd_valve-status = "UF-Permeate Drain/BW Fill Valve State"
air_valve-opening-command = "NA"
feed-pump-speed-command = "UF-P1 (%)"
supply-tank-out-speed-command = "DP1-Speed (%)"
backwash_dosing_pump-flow-rate = "DP4 Flowrate (mL/min)"
backwash_dosing_pump-speed-command = "DP4-Speed (%)"
backwash_tank-volume = "BW-Backwash Tank Volume (gal)"

[unit]
conn-b3w1_valve-to-uf_bypass_valve-flow-rate = "GAL_US-PER-MIN"
conn-b3w1_valve-to-uf_bypass_valve-ph = "PH"
conn-b3w1_valve-to-uf_bypass_valve-pressure = "PSI"
conn-b3w1_valve-to-uf_bypass_valve-toc-ppm = "PPM"
conn-uf-unit-to-reject_valve-pressure = "PSI"
feed-pump-electric-current = "A"
feed-pump-out-flow-rate = "GAL_US-PER-MIN"
feed-pump-out-pressure = "PSI"
supply-tank-out-flow-rate = "MilliL-PER-MIN"
uf-feed-tank-temperature = "DEG_C"
uf-feed-tank-volume = "GAL_US"
uf-unit-out-turbidity = "NTU"
backwash_dosing_pump-flow-rate = "MilliL-PER-MIN"
backwash_tank-volume = "GAL_US"

[topic]
ac_valve-status = "sensor/uf_air_scour_valve_state"
b1-valve-status = "sensor/uf_b1_state"
b3w1_valve-status = "sensor/uf_b3w1_state"
b3w2-valve-status = "sensor/uf_b3w2_state"
conn-b3w1_valve-to-uf_bypass_valve-flow-rate = "sensor/uf_permeate_flow_gpm"
conn-b3w1_valve-to-uf_bypass_valve-ph = "sensor/uf_permeate_ph"
conn-b3w1_valve-to-uf_bypass_valve-pressure = "sensor/uf_permeate_pressure_psi"
conn-b3w1_valve-to-uf_bypass_valve-toc-ppm = "sensor/mult_toc_1_ppm"
conn-uf-unit-to-reject_valve-pressure = "sensor/uf_reject_pressure_psi"
feed-pump-electric-current = "sensor/uf_current_draw_a"
feed-pump-out-flow-rate = "sensor/uf_feed_flow_gpm"
feed-pump-out-pressure = "sensor/uf_feed_pressure_psi"
s2_valve-status = "sensor/uf_purge_valve_state"
supply-tank-out-flow-rate = "sensor/dp1_flowrate_ml_min"
uf-feed-tank-temperature = "sensor/uf_feed_temperature_c"
uf-feed-tank-volume = "sensor/uf_feed_volume_gal"
uf-unit-out-turbidity = "sensor/uf_turbidity_ntu"
uf_backwash_pump-status = "sensor/uf_backwash_pump_state"
ufd_valve-status = "sensor/uf_permeate_drain_bw_fill_valve_state"
air_valve-opening-command = "na"
feed-pump-speed-command = "sensor/uf_p1_percent"
supply-tank-out-speed-command = "sensor/dp1_speed_percent"
backwash_dosing_pump-flow-rate = "sensor/backwash_dosing_pump_flow_gpm"
backwash_dosing_pump-speed-command = "sensor/backwash_dosing_pump_speed_percent"
backwash_tank-volume = "sensor/backwash_tank_volume_gal"

[threshold_high]
feed-pump-out-flow-rate = 5
conn-b3w1_valve-to-uf_bypass_valve-flow-rate = 5
uf-feed-tank-volume = 27
feed-pump-out-pressure = 20
backwash_tank-volume = 250

[threshold_low]
uf-feed-tank-volume = 7
backwash_tank-volume = 60

[label]
ac_valve-status = "UF Valve AC: Status"
b1-valve-status = "UF Valve B1: Status"
b3w1_valve-status = "UF Valve B3W1: Status"
b3w2-valve-status = "UF Valve B3W2: Status"
conn-b3w1_valve-to-uf_bypass_valve-flow-rate = "B3W1 to UF Bypass: Flow"
conn-b3w1_valve-to-uf_bypass_valve-ph = "B3W1 to UF Bypass: pH"
conn-b3w1_valve-to-uf_bypass_valve-pressure = "B3W1 to UF Bypass: Pressure"
conn-b3w1_valve-to-uf_bypass_valve-toc-ppm = "B3W1 to UF Bypass: TOC"
conn-uf-unit-to-reject_valve-pressure = "UF to Reject: Pressure"
feed-pump-electric-current = "Feed Pump: Current"
feed-pump-out-flow-rate = "Feed Pump: Flow"
feed-pump-out-pressure = "Feed Pump: Pressure"
s2_valve-status = "UF Valve S2: Status"
supply-tank-out-flow-rate = "Supply Tank: Outflow"
uf-feed-tank-temperature = "UF Feed: Temp"
uf-feed-tank-volume = "UF Feed: Volume"
uf-unit-out-turbidity = "UF Permeate: Turbidity"
uf_backwash_pump-status = "UF Backwash Pump: Status"
ufd_valve-status = "UF Valve UFD: Status"
air_valve-opening-command = "Air Valve: Status"
feed-pump-speed-command = "Feed Pump: Speed"
supply-tank-out-speed-command = "Supply Tank: Speed"
backwash_dosing_pump-flow-rate = "Backwash Dosing: Flow"
backwash_dosing_pump-speed-command = "Backwash Dosing: Speed"
backwash_tank-volume = "Backwash Tank: Volume"
