tank:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:Tank ;
      rdfs:label P:label ;
      s223:hasConnectionPoint P:in, P:out, P:bi-cp ;
      s223:cnx P:in, P:out, P:bi-cp ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
    - template: bidirectional-cp
      args: {"name": "bi-cp"}
  optional: ["role", "bi-cp", "in", "out", "label"]

basin:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:Basin ;
      rdfs:label P:label ;
      s223:hasConnectionPoint P:in, P:out, P:drain, P:overflow ;
      s223:cnx P:in, P:out, P:drain, P:overflow ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
    - template: outlet-cp
      args: {"name": "drain"}
    - template: outlet-cp
      args: {"name": "overflow"}
  optional: ["role", "in", "out", "overflow", "drain", "label"]


bladder:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:Tank ;
      rdfs:label P:label ;
      s223:hasConnectionPoint P:in, P:out ;
      s223:cnx P:in, P:out ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
  optional: ["role", "label"]

valve:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:Valve ;
      rdfs:label P:label ;
      s223:hasConnectionPoint P:in, P:out ;
      s223:cnx P:in, P:out ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
  optional: ["role", "label"]

filter:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:Filter ;
      rdfs:label P:label ;
      s223:hasConnectionPoint P:in, P:out ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
  optional: ["role", "label"]

membrane:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:Membrane ;
      rdfs:label P:label ;
      s223:hasConnectionPoint P:in, P:out ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
  optional: ["role", "label"]

membrane-module:
# Membrane module may in reality contain many membranes
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:Equipment ;
      rdfs:label P:label ;
      s223:contains P:membrane ;
      s223:hasConnectionPoint P:in, P:out ;
      s223:hasRole P:role .
    P:membrane-in s223:mapsTo P:in .
    P:membrane-out s223:mapsTo P:out .

  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
    - template: membrane
      args: {"name": "membrane", "in":"membrane-in", "out":"membrane-out"}
  optional: ["role", "label"]

pump:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:Pump ;
      rdfs:label P:label ;
      s223:hasConnectionPoint P:in, P:out ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
  optional: ["role", "label"]

check-valve:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:CheckValve ;
      rdfs:label P:label ;
      s223:hasConnectionPoint P:in, P:out ;
      s223:cnx P:in, P:out ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
  optional: ["role", "label"]

vfd:
# can either just have a vfd, or make a vfd with a pump
# make connectionpoints optional for VFD, since we don't really do elecricity for controls
# In s223 VFD's have required electrical connection points, would probably be easier to make a vfd with a pump template
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:VariableFrequencyDrive ;
      rdfs:label P:label ;
      s223:hasConnectionPoint P:in, P:out ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
  optional: ["role", "label"]

pump-with-vfd:
# I don't recall if this was the agreed upon modeling convention
# Took a first guess at properties
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:Pump ;
      rdfs:label P:label ;
      s223:hasConnectionPoint P:in, P:out, P:elec-in ;
      s223:contains P:vfd-name, P:pump-name ;
      s223:hasProperty P:on-off-command, P:speed-command .

    P:pump-in s223:mapsTo P:in .
    P:pump-out s223:mapsTo P:out .

    P:pump-name s223:hasConnectionPoint P:pump-elec-in ;
      s223:cnx P:pump-elec-in ;
      s223:hasMedium P:elec-medium .

    P:vfd-name s223:mapsTo P:elec-in ;
      s223:connectsTo P:pump-name .

    P:vfd-in s223:mapsTo P:elec-in .
    P:vfd-out s223:cnx P:pump-elec-in .

  dependencies:
  - template: inlet-cp
    args: {"name": "in"}
  - template: inlet-cp
    args: {"name": "elec-in"}
  - template: outlet-cp
    args: {"name": "out"}
  - template: on-off-command
    args: {"name": "on-off-command"}
  - template: speed-command
    args: {"name": "speed-command"}
  - template: pump
    args: {"name": "pump-name", "in":"pump-in", "out":"pump-out"}
  - template: vfd
    args: {"name": "vfd-name", "in":"vfd-in", "out":"vfd-out"}
  optional: ["label"]

controller:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:Controller ;
      rdfs:label P:label .
  optional: ["label"]


uf-unit:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:UltrafiltrationUnit ;
      rdfs:label P:label ;
      s223:hasConnectionPoint P:in, P:out ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
  optional: ["role", "label"]

uv-reactor:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:UltravioletLightUnit ;
      rdfs:label P:label ;
      watr:hasProcess watr:Process-UVDisinfection ;
      s223:hasConnectionPoint P:in, P:out ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
  optional: ["role", "label"]

contact-chamber:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:DisinfectionUnit ;
      rdfs:label P:label ;
      watr:hasProcess watr:Process-Disinfection ;
      s223:hasConnectionPoint P:in, P:out ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
  optional: ["role", "label"]

sensor:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a s223:Sensor ;
      rdfs:label P:label ;
      s223:observes P:property ;
      s223:hasObservationLocation P:where .
  optional: ["property", "where", "label"]


concentration-sensor:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix qudt: <http://qudt.org/schema/qudt/> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a s223:Sensor ;
      rdfs:label P:label ;
      s223:observes P:property ;
      s223:hasObservationLocation P:where .
    P:property qudt:hasUnit P:unit ;
      s223:ofConstituent P:substance .
  optional: ["where", "label"]
  dependencies:
   - template: quantifiable-property
     args: {"name": "property", "unit": "unit", "substance": "constituent", "property-unit": "unit", "property-constituent": "substance"}

flocculation-basin:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:FlocculationBasin ;
      rdfs:label P:label ;
      watr:hasProcess watr:Process-Flocculation ;
      s223:hasConnectionPoint P:in, P:out, P:drain, P:overflow ;
      s223:cnx P:in, P:out, P:drain, P:overflow ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
    - template: outlet-cp
      args: {"name": "drain"}
    - template: outlet-cp
      args: {"name": "overflow"}
  optional: ["role", "in", "out", "overflow", "drain", "label"]

sedimentation-tank:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:SedimentationTank ;
      rdfs:label P:label ;
      watr:hasProcess watr:Process-Sedimentation ;
      s223:hasConnectionPoint P:in, P:out ;
      s223:cnx P:in, P:out ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
  optional: ["role", "in", "out", "label"]

filtration:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:Filter ;
      rdfs:label P:label ;
      watr:hasProcess watr:Process-Filtration ;
      s223:hasConnectionPoint P:in, P:out ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
  optional: ["role", "label"]

disinfection-unit:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:DisinfectionUnit ;
      rdfs:label P:label ;
      watr:hasProcess watr:Process-Disinfection ;
      s223:hasConnectionPoint P:in, P:out ;
      s223:cnx P:in, P:out ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
  optional: ["role", "in", "out", "label"]

chlorination-unit:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:ChlorinationUnit ;
      rdfs:label P:label ;
      watr:hasProcess watr:Process-Chlorination ;
      s223:hasConnectionPoint P:in, P:out ;
      s223:cnx P:in, P:out ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
  optional: ["role", "in", "out", "label"]

rapid-sand-filter:
  body: >
    @prefix P: <urn:___param___#> .
    @prefix s223: <http://data.ashrae.org/standard223#> .
    @prefix watr: <urn:nawi-water-ontology#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    P:name a watr:RapidSandFilter ;
      rdfs:label P:label ;
      watr:hasProcess watr:Process-RapidSandFiltration ;
      s223:hasConnectionPoint P:in, P:out ;
      s223:hasRole P:role .
  dependencies:
    - template: inlet-cp
      args: {"name": "in"}
    - template: outlet-cp
      args: {"name": "out"}
  optional: ["role", "label"]
